version: '3'
services:
    ubuntu-pkg:
        build:
            context: .
            dockerfile: Dockerfile
    ubuntu-bin:
        build:
            context: .
            dockerfile: Dockerfile
    ubuntu-src:
        build:
            context: .
            dockerfile: Dockerfile
