version: '3'
services:
    ubuntu-pkg:
        build:
            context: .
            dockerfile: Dockerfile
            target: ubuntu-pkg
    ubuntu-bin:
        build:
            context: .
            dockerfile: Dockerfile
            target: ubuntu-bin
    ubuntu-src:
        build:
            context: .
            dockerfile: Dockerfile
            target: ubuntu-src
